import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'My Car Shop',
  description: 'Generated by me'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-7xl px-4">
          <div className="mx-auto max-w-3xl">
            <h2 className="py-5 text-3xl font-bold tracking-tight text-gray-900">
              <Link href={'/'}>Martin's Velocity Vault</Link>
            </h2>
            <ul className="flex mb-2">
              <li className="flex-1 mr-2">
                <Link href={'/'} className="nav-item">Home (Car List)</Link>
              </li>
              <li className="flex-1 mr-2">
                <Link href={'/car/new'} className="nav-item">New Car</Link>
              </li>
            </ul>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
